question_data = [{"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Seoul is the capital of North Korea.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Celebrities", "type": "boolean", "difficulty": "medium",
                  "question": "Michael Jackson had a pet python named 'Crusher'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "'Typewriter'; is the longest word that can be typed using "
                              "only the first row on a QWERTY keyboard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "There are no roads in/out of Juneau, Alaska.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Super Mario Bros. was released in 1990.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "All program codes have to be compiled into an executable file "
                              "in order to be run. This file can then be executed on any machine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "In World War II, Hawker Typhoons served in the Pacific theater.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "medium",
                  "question": "The M41 Walker Bulldog remains in service in some countries to this day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Steel is an alloy of Iron and Carbon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium", "question": "Shrimp can swim backwards.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Tony Hawk's Pro Skater was released in 1999.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The Xenomorph from the science fiction film 'Alien'; has acidic blood.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium", "question": "MacOS is based on Linux.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The open source program Redis is a relational database server.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The French word to travel is 'Travail'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "When BMW was established in 1916, it was producing automobiles.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "The average lifespan of a wildcat is only around 5-6 years. ",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Antarctica is the largest desert in the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "medium",
                  "question": "'Twenty One Pilots'; made the song &quot;The Motion&quot; featuring Sampha.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Pistons were added to Minecraft in Beta 1.5.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Fast food restaurant chains Carl's Jr. and "
                              "Hardee's are owned by the same company.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Pink Guy's debut album was 'Pink Season'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Like his character in 'Parks and Recreation', Aziz "
                              "Ansari was born in South Carolina.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In the video game 'Transistor', 'Red' is "
                              "the name of the main character.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Norway has a larger land area than Sweden.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Klingons once had a period of Democracy in their history, "
                              "they referred to it as the 'Dark Times'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "'Santa Claus' is a variety of melon.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 'Call Of Duty: World At War', the first appearance of "
                              "the 'PPSH-41' in 'Zombies' was in the map 'Der Riese'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 'Call Of Duty: Zombies', you can upgrade the 'Apothicon "
                              "Servant' in the 'Shadows Of Evil' map.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "medium",
                  "question": "In 'To Love-Ru: Darkness', Yami reveals her real name is Eve.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The Fiat Multipla is a drivable car in 'Forza Horizon 3'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "Finnish Lapphund dogs were used for herding reindeer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 'Star Trek: The Next Generation', Data is the only android in existence.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The majority of Subaru vehicles are made in China.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "medium",
                  "question": "An episode of 'The Simpsons' is dedicated to Moe Szyslak's bar rag.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Sports", "type": "boolean", "difficulty": "medium",
                  "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have "
                              "been used in matches.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Nutcracker Suite was one of the musical pieces featured in Disney's 1940's "
                              "film Fantasia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby's "
                              "All-Star Laff-a-Lympics.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the "
                              "snack on the streets of Chicago.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Art", "type": "boolean", "difficulty": "medium",
                  "question": "Venus of Willendorf is one of the earliest works of art, depicting the "
                              "planets Mars and Venus embrace in the heavens at night.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The most frequent subconscious activity repeated by the human body is blinking.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The pickled gherkin was first added to hamburgers because a US health law "
                              "required all fast-food to include a source of Vitamin C.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                  "question": "The snowmobile was invented by Canadian Joseph-Armand Bombardier in 1937.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Minecraft wasn't the original name to Minecraft.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "medium",
                  "question": "Green Day's album 'American Idiot' is considered "
                              "a 'punk rock opera'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "medium",
                  "question": "In 'Resident Evil', only Chris has access to the grenade launcher.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
